### ISSUE TITLE
About an application bug

### ISSUE THREAD

**Issue by hewittzgh** [acoular/spectacoular#4]
Hello, when I ran the example according to the manual, I found an error: in the application of "microphone array measurement app", the code in line 47 of main.py `from spectral import rectgrid, calibhelper, filtoctavelive, timeinoutpresenter, filtoctave` in filtoctave does not exist. Maybe you forgot to update the app when updating the version?
```PS D:\Document\spectacoular\spectacoular-master\spectacoular-master\apps> bokeh serve --show  Measurement_App --args --device=phantom --blocksize=256
2021-10-16 03:48:28,725 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-10-16 03:48:28,727 User authentication hooks NOT provided (default user enabled)
2021-10-16 03:48:28,733 Bokeh app running at: http://localhost:5006/Measurement_App
2021-10-16 03:48:28,733 Starting Bokeh server with process id: 324420
2021-10-16 03:48:33,230 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x0000021C51604250>: cannot import name 'FiltOctave' from 'spectacoular' (D:\Application\anaconda3\envs\spect
acoular\lib\site-packages\spectacoular\__init__.py)
File "main.py", line 47, in <module>:
from spectacoular import RectGrid,CalibHelper,FiltOctaveLive,TimeInOutPresenter,FiltOctave Traceback (most recent call last):
  File "D:\Application\anaconda3\envs\spectacoular\lib\site-packages\bokeh\application\handlers\code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "D:\Document\spectacoular\spectacoular-master\spectacoular-master\apps\Measurement_App\main.py", line 47, in <module>
    from spectacoular import RectGrid,CalibHelper,FiltOctaveLive,TimeInOutPresenter,FiltOctave
ImportError: cannot import name 'FiltOctave' from 'spectacoular' (D:\Application\anaconda3\envs\spectacoular\lib\site-packages\spectacoular\__init__.py)

2021-10-16 03:48:33,459 WebSocket connection opened
2021-10-16 03:48:33,461 ServerConnection created
2021-10-16 03:48:34,511 WebSocket connection closed: code=1001, reason=None```

**Comment by dimakozin** [comment]
Just copied spectacoular files from repository to anaconda3\Lib\site-packages\spectacoular
